export const lightColors = {
  systemPrimaryBackground: '#fff',
  systemSecondaryBackground: '#fff',
  systemTertiaryBackground: '#f2f2f7',
  systemQuaternaryBackground: '#fff',
  systemHighlight: '#e5e5ea',
  systemForeground: '#000',
  systemRed: '#ff3b30',
  systemGreen: '#34c759',
  systemBlue: '#007bff',
  systemOrange: '#ff9500',
  systemYellow: '#ffcc00',
  systemTeal: '#5ac7fa',
  systemPurple: '#af52de',
  systemPink: '#ff2d54',
  systemIndigo: '#5856d6',
  systemGray: '#8e8e93',
  systemGray2: '#aeaeb2',
  systemGray3: '#c7c7cc',
  systemGray4: '#d1d1d6',
  systemGray5: '#e5e5ea',
  systemGray6: '#f2f2f7',
};

export const darkColors = {
  systemPrimaryBackground: '#000',
  systemSecondaryBackground: '#2c2c2e',
  systemTertiaryBackground: '#000',
  systemQuaternaryBackground: '#1c1c1e',
  systemHighlight: '#3a3a3c',
  systemForeground: '#fff',
  systemRed: '#ff3b30',
  systemGreen: '#30d158',
  systemBlue: '#0a84ff',
  systemOrange: '#ff9500',
  systemYellow: '#ffcc00',
  systemTeal: '#64d2ff',
  systemPurple: '#bf5af2',
  systemPink: '#ff375f',
  systemIndigo: '#5e5ce6',
  systemGray: '#8e8e93',
  systemGray2: '#636366',
  systemGray3: '#48484a',
  systemGray4: '#3a3a3c',
  systemGray5: '#2c2c2e',
  systemGray6: '#1c1c1e',
};

export const Colors = {
  light: lightColors,
  dark: darkColors,
};
